[project]
name = "jaffle-shop-duckdb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "dbt-core>=1.7.9,<1.8.0",
    "dbt-duckdb>=1.7.3,<1.8.0",
    "duckcli>=0.2.1",
    "pandas>=1.5.3",
    "sqlfluff>=2.3.5,<3",
]
